const mongoose = require('mongoose');

const NodeDraftsSchema = new mongoose.Schema({
  id: { type: String, required: true },
  tenantConfigId: { type: String, required: true },
  createdBy: { type: String, required: true },
  type: { type: String, required: true },
  appId: { type: String, required: true },
  appType: { type: String, enum: ['workflows', 'analytics'] },
  z: { type: String },
  swaggerDoc: { type: String },
  paytoqs: { type: String },
  persist: { type: Boolean },
  proxy: { type: String },
  senderr: { type: Boolean },
  insecureHTTPParser: { type: Boolean },
  authType: { type: String },
  tls: { type: String },
  label: { type: String },
  disabled: { type: Boolean },
  info: { type: String },
  env: { type: mongoose.Schema.Types.Mixed },
  credentials: { type: mongoose.Schema.Types.Mixed },
  name: { type: String },
  active: { type: Boolean },
  wires: { type: mongoose.Schema.Types.Mixed },
  x: { type: Number },
  y: { type: Number },
  func: { type: String },
  outputs: { type: Number },
  timeout: { type: String },
  noerr: { type: Number },
  initialize: { type: String },
  finalize: { type: String },
  libs: { type: mongoose.Schema.Types.Mixed },
  rules: { type: mongoose.Schema.Types.Mixed },
  property: { type: String },
  headers: { type: mongoose.Schema.Types.Mixed },
  method: { type: String },
  url: { type: String },
  statusCode: { type: String },
  payload: { type: String },
  topic: { type: String },
  sep: { type: String },
  hdrin: { type: Boolean },
  hdrout: { type: String },
  isPopulated: { type: Boolean, default: false }, //this flag is used when subflows are populated and while deleting flows from any app we can avoid accidently deleting subflows
  in: { type: mongoose.Schema.Types.Mixed }, //subFlowNode
  out: { type: mongoose.Schema.Types.Mixed },
  category: { type: String },
  color: { type: String },
  meta: { type: Object },
  upload: { type: Boolean }, //httpin
  swaggerDoc: { type: String },
  insecureHTTPParser: { type: Boolean }, //httpRequestNode
  authType: { type: String },
  paytoqs: { type: String },
  persist: { type: Boolean },
  proxy: { type: String },
  ret: { type: String },
  senderr: { type: Boolean },
  tls: { type: String },
  addname: { type: String }, //splitnode
  arraySplt: { type: Number },
  arraySpltType: { type: String },
  splt: { type: String },
  spltType: { type: String },
  stream: { type: Boolean },
  accumulate: { type: Boolean }, //joinnode
  build: { type: String },
  count: { type: String },
  joiner: { type: String },
  joinerType: { type: String },
  key: { type: String },
  mode: { type: String },
  propertyType: { type: String },
  reduceExp: { type: String },
  reduceFixup: { type: String },
  reduceInit: { type: String },
  reduceInitTye: { type: String },
  reduceRight: { type: Boolean },
  useparts: { type: Boolean },
  action: { type: String }, //changeNode
  from: { type: String },
  to: { type: String },
  reg: { type: Boolean },
  scope: { type: mongoose.Schema.Types.Mixed }, //debugNode
  uncaught: { type: Boolean },
  complete: { type: String },
  console: { type: Boolean },
  statusType: { type: String },
  statusVal: { type: String },
  tosidebar: { type: Boolean },
  tostatus: { type: Boolean },
  commandResponseMsgOutput: { type: String },
  defaultLocation: { type: String },
  defaultLocationType: { type: String },
  options: { type: [mongoose.Schema.Types.Mixed] },
  outputField: { type: String },
  storeName: { type: String },
  timeZone: { type: String },
  once: { type: Boolean },
  onceDelay: { type: Number },
  crontab: { type: String },
  payloadType: { type: String },
  props: { type: [mongoose.Schema.Types.Mixed] },
  repeat: { type: String },
  recStatus: { type: String, default: 'active' }
});

const NodeDrafts = mongoose.model('nodeDrafts', NodeDraftsSchema);
module.exports = NodeDrafts;
